# Generated by Django 3.0.3 on 2020-02-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='bagging_date',
            field=models.DateTimeField(),
        ),
    ]
