# Generated by Django 3.0.3 on 2020-03-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mockup', '0004_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='date_uploaded',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockup.UploadSession'),
        ),
    ]
