# Generated by Django 3.1.1 on 2020-09-15 15:07
# Edited manually by Daniel Lovegrove

from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    # Able to transfer
    group, created = Group.objects.get_or_create(name="transfer_user")

    # Archivist
    group, created = Group.objects.get_or_create(name="archivist_user")


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
