# Generated by Django 3.1.1 on 2020-09-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0003_auto_20200915_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='report_contents',
        ),
        migrations.AddField(
            model_name='bag',
            name='caais_metadata',
            field=models.TextField(default='{}'),
        ),
    ]
