# Generated by Django 3.1.1 on 2020-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0004_auto_20200925_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmed_email',
            field=models.BooleanField(default=False),
        ),
    ]
