# Generated by Django 3.1.1 on 2020-11-17 02:33

from django.db import migrations, models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0008_auto_20201105_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='attached_file',
            field=models.FileField(blank=True, null=True, storage=recordtransfer.storage.OverwriteStorage(), upload_to='jobs/zipped_bags'),
        ),
    ]
