# Generated by Django 3.1.1 on 2021-04-28 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0012_auto_20201208_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='part_of_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.baggroup'),
        ),
    ]
