# Generated by Django 3.1.8 on 2021-05-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0015_auto_20210528_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='right',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
