# Generated by Django 3.1.8 on 2021-09-09 15:24

from django.db import migrations, models
from django.core.management.sql import emit_post_migrate_signal
from django.contrib.auth.models import Group, Permission

from caais.models import SourceType, SourceRole


def populate_initial_terms(apps, schema_editor):
    other_type = SourceType.objects.filter(name="Other").first()
    if not other_type:
        SourceType.objects.create(
            name="Other",
            description="Placeholder right to allow user to specify unique source type",
        )

    other_role = SourceRole.objects.filter(name="Other").first()
    if not other_role:
        SourceRole.objects.create(
            name="Other",
            description="Placeholder right to allow user to specify unique source role",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0016_auto_20210528_1228"),
    ]

    operations = [
        migrations.RunPython(populate_initial_terms),
    ]
