# Generated by Django 3.2.11 on 2022-01-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0020_appraisal_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.uploadsession'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bagging_date',
            field=models.DateTimeField(null=True),
        ),
    ]
