# Generated by Django 3.2.11 on 2022-01-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0021_auto_20220113_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
