# Generated by Django 3.2.11 on 2022-01-19 20:33
# Modified 2025-08-21 15:55 to facilitate moving file uploads to upload app

import upload.models
import upload.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    """Update the UploadedFile model's fields."""

    dependencies = [  # noqa: RUF012
        ("recordtransfer", "0023_bag_uuid"),
    ]

    operations = [  # noqa: RUF012
        migrations.RemoveField(
            model_name="uploadedfile",
            name="old_copy_removed",
        ),
        migrations.RemoveField(
            model_name="uploadedfile",
            name="path",
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="file_upload",
            field=models.FileField(
                null=True,
                storage=upload.storage.UploadedFileStorage,
                upload_to=upload.models.session_upload_location,
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="name",
            field=models.CharField(default="-", max_length=256, null=True),
        ),
    ]
