# Generated by Django 3.2.11 on 2022-04-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0024_auto_20220119_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gets_notification_emails',
            field=models.BooleanField(default=True),
        ),
    ]
