# Generated by Django 3.2.11 on 2022-03-25 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0025_user_gets_notification_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(unique=True)),
                ('current_step', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('step_data', models.BinaryField(default=b'')),
            ],
        ),
    ]
