# Generated by Django 3.2.20 on 2023-10-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0031_auto_20230728_1418'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appraisal',
        ),
    ]
