# Generated by Django 3.2.23 on 2024-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0033_remove_submission_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='raw_form',
            field=models.BinaryField(default=b'', null=True),
        ),
        migrations.AlterField(
            model_name='savedtransfer',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
