# Generated by Django 3.2.25 on 2024-10-30 15:38

from django.db import migrations, models
import django.db.models.deletion


def delete_null_submission_groups(apps, schema_editor):
    """Delete SubmissionGroup instances with null created_by field"""
    SubmissionGroup = apps.get_model("recordtransfer", "SubmissionGroup")
    SubmissionGroup.objects.filter(created_by=None).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0035_submissiongroup_uuid"),
    ]

    operations = [
        migrations.RunPython(
            code=delete_null_submission_groups,
        ),
        migrations.AlterField(
            model_name="submissiongroup",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recordtransfer.user"
            ),
        ),
    ]
