# Generated by Django 4.2.16 on 2024-11-08 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0035_inprogresssubmission_delete_savedtransfer'),
        ('recordtransfer', '0036_alter_submissiongroup_created_by'),
    ]

    operations = [
    ]
