# Generated by Django 4.2.17 on 2024-12-10 03:35

from django.db import migrations

from caais.models import SourceRole, SourceType


def populate_required_terms(apps, schema_editor):
    individual_type, created = SourceType.objects.get_or_create(
        name="Individual",
        description="An individual person.",
    )
    if created:
        individual_type.save()

    donor_role, created = SourceRole.objects.get_or_create(
        name="Donor",
        description="The entity is the donor of the records.",
    )
    if created:
        donor_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0038_inprogresssubmission_title"),
    ]

    operations = [
        migrations.RunPython(populate_required_terms),
    ]
