# Generated by Django 4.2.17 on 2024-12-10 03:35

from django.db import migrations

from caais.models import SourceRole, SourceType


def populate_required_terms(apps, schema_editor):
    individual = SourceType.objects.filter(name="Individual").first()
    if not individual:
        SourceType.objects.create(
            name="Individual", description="An individual person."
        )

    donor = SourceRole.objects.filter(name="Donor").first()
    if not donor:
        SourceRole.objects.create(
            name="Donor", description="An entity that donates records."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0038_inprogresssubmission_title"),
    ]

    operations = [
        migrations.RunPython(populate_required_terms),
    ]
