# Generated by Django 4.2.17 on 2025-01-07 16:14

from django.db import migrations, models
import recordtransfer.models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0039_source_info_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inprogresssubmission',
            name='current_step',
            field=models.CharField(choices=[('acceptlegal', 'ACCEPT_LEGAL'), ('contactinfo', 'CONTACT_INFO'), ('sourceinfo', 'SOURCE_INFO'), ('recorddescription', 'RECORD_DESCRIPTION'), ('rights', 'RIGHTS'), ('otheridentifiers', 'OTHER_IDENTIFIERS'), ('grouptransfer', 'GROUP_TRANSFER'), ('uploadfiles', 'UPLOAD_FILES'), ('finalnotes', 'FINAL_NOTES'), ('review', 'REVIEW')], help_text='Current step in the transfer wizard process', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_upload',
            field=models.FileField(null=True, storage=recordtransfer.storage.TempFileStorage, upload_to=recordtransfer.models.session_upload_location),
        ),
    ]
