# Generated by Django 4.2.17 on 2025-01-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0040_alter_inprogresssubmission_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='temp',
            field=models.BooleanField(default=True),
        ),
    ]
