# Generated by Django 4.2.19 on 2025-03-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0044_uploadsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submission',
        ),
    ]
