# Generated by Django 4.2.19 on 2025-02-18 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0044_uploadsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogresssubmission',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.uploadsession'),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='last_upload_interaction_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
