# Generated by Django 4.2.18 on 2025-02-26 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [
        ("recordtransfer", "0045_inprogresssubmission_upload_session_and_more"),
        ("recordtransfer", "0046_alter_uploadsession_last_upload_interaction_time"),
        ("recordtransfer", "0047_inprogresssubmission_reminder_email_sent"),
    ]

    dependencies = [
        ("recordtransfer", "0044_uploadsession_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="inprogresssubmission",
            name="upload_session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recordtransfer.uploadsession",
            ),
        ),
        migrations.AddField(
            model_name="uploadsession",
            name="last_upload_interaction_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name="inprogresssubmission",
            name="reminder_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
