# Generated by Django 4.2.19 on 2025-03-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0045_job_message_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submission',
        ),
    ]
