# Generated by Django 4.2.19 on 2025-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0045_inprogresssubmission_upload_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsession',
            name='last_upload_interaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
