# Generated by Django 4.2.19 on 2025-02-26 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0045_uploadsession_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogresssubmission',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
