# Generated by Django 4.2.19 on 2025-03-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0046_uploadsession_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="message_log",
            field=models.TextField(null=True),
        ),
    ]
