# Generated by Django 4.2.19 on 2025-02-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0046_alter_uploadsession_last_upload_interaction_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogresssubmission',
            name='reminder_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
