# Generated by Django 4.2.19 on 2025-02-28 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0046_alter_uploadsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inprogresssubmission',
            name='upload_session',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_progress_submission', to='recordtransfer.uploadsession'),
        ),
    ]
