# Generated by Django 4.2.19 on 2025-03-06 15:07

from django.db import migrations, models
import recordtransfer.storage


class Migration(migrations.Migration):

    replaces = [('recordtransfer', '0047_job_message_log'), ('recordtransfer', '0048_alter_job_attached_file'), ('recordtransfer', '0049_remove_job_submission')]

    dependencies = [
        ('recordtransfer', '0046_uploadsession_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='message_log',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='attached_file',
            field=models.FileField(blank=True, null=True, storage=recordtransfer.storage.OverwriteStorage, upload_to='jobs/attachments'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='submission',
        ),
    ]
