# Generated by Django 4.2.19 on 2025-03-05 20:53

from django.db import migrations, models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0047_job_message_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='attached_file',
            field=models.FileField(blank=True, null=True, storage=recordtransfer.storage.OverwriteStorage, upload_to='jobs/attachments'),
        ),
    ]
