# Generated by Django 4.2.20 on 2025-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0047_job_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inprogresssubmission',
            name='current_step',
            field=models.CharField(choices=[('acceptlegal', 'ACCEPT_LEGAL'), ('contactinfo', 'CONTACT_INFO'), ('sourceinfo', 'SOURCE_INFO'), ('recorddescription', 'RECORD_DESCRIPTION'), ('rights', 'RIGHTS'), ('otheridentifiers', 'OTHER_IDENTIFIERS'), ('groupsubmission', 'GROUP_SUBMISSION'), ('uploadfiles', 'UPLOAD_FILES'), ('finalnotes', 'FINAL_NOTES'), ('review', 'REVIEW')], help_text='Current step in the transfer wizard process', max_length=20),
        ),
    ]
