# Generated by Django 4.2.19 on 2025-03-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0048_alter_job_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='submission',
        ),
    ]
