# Generated by Django 4.2.20 on 2025-06-09 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_site_settings(apps, schema_editor):
    """Populate SiteSetting model with initial values."""
    SiteSetting = apps.get_model("recordtransfer", "SiteSetting")

    settings_mapping = {
        # Email settings
        "ARCHIVIST_EMAIL": "archivist@example.com",
        "DO_NOT_REPLY_USERNAME": "do-not-reply",
        # Pagination
        "PAGINATE_BY": "10",
        # CAAIS defaults
        "CAAIS_DEFAULT_REPOSITORY": "",
        "CAAIS_DEFAULT_ACCESSION_TITLE": "",
        "CAAIS_DEFAULT_ARCHIVAL_UNIT": "",
        "CAAIS_DEFAULT_DISPOSITION_AUTHORITY": "",
        "CAAIS_DEFAULT_ACQUISITION_METHOD": "",
        "CAAIS_DEFAULT_STATUS": "",
        "CAAIS_DEFAULT_SOURCE_CONFIDENTIALITY": "",
        "CAAIS_DEFAULT_PRELIMINARY_CUSTODIAL_HISTORY": "",
        "CAAIS_DEFAULT_DATE_OF_MATERIALS": "",
        "CAAIS_DEFAULT_EXTENT_TYPE": "",
        "CAAIS_DEFAULT_QUANTITY_AND_UNIT_OF_MEASURE": "",
        "CAAIS_DEFAULT_CONTENT_TYPE": "",
        "CAAIS_DEFAULT_CARRIER_TYPE": "",
        "CAAIS_DEFAULT_EXTENT_NOTE": "",
        "CAAIS_DEFAULT_PRELIMINARY_SCOPE_AND_CONTENT": "",
        "CAAIS_DEFAULT_LANGUAGE_OF_MATERIAL": "",
        "CAAIS_DEFAULT_STORAGE_LOCATION": "",
        "CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_TYPE": "",
        "CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_VALUE": "",
        "CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_NOTE": "",
        "CAAIS_DEFAULT_APPRAISAL_TYPE": "",
        "CAAIS_DEFAULT_APPRAISAL_VALUE": "",
        "CAAIS_DEFAULT_APPRAISAL_NOTE": "",
        "CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_TYPE": "",
        "CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_TITLE": "",
        "CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_NOTE": "",
        "CAAIS_DEFAULT_GENERAL_NOTE": "",
        "CAAIS_DEFAULT_RULES_OR_CONVENTIONS": "",
        "CAAIS_DEFAULT_LANGUAGE_OF_ACCESSION_RECORD": "",
        # CAAIS event defaults
        "CAAIS_DEFAULT_EVENT_TYPE": "Transfer Submitted",
        "CAAIS_DEFAULT_EVENT_AGENT": "",
        "CAAIS_DEFAULT_EVENT_NOTE": "",
        # CAAIS creation defaults
        "CAAIS_DEFAULT_CREATION_TYPE": "Creation",
        "CAAIS_DEFAULT_CREATION_AGENT": "",
        "CAAIS_DEFAULT_CREATION_NOTE": "",
    }

    # Create SiteSetting objects for each setting
    settings_to_create = []
    for key, value in settings_mapping.items():
        settings_to_create.append(SiteSetting(key=key, value=str(value)))

    # Bulk create all settings
    SiteSetting.objects.bulk_create(settings_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0049_remove_user_confirmed_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
                (
                    "change_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Change date"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_site_settings, reverse_code=migrations.RunPython.noop),
    ]
