# Generated by Django 4.2.20 on 2025-06-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0049_remove_user_confirmed_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tempuploadedfile',
            options={'verbose_name': 'File Currently Being Uploaded', 'verbose_name_plural': 'Files Currently Being Uploaded'},
        ),
    ]
