# Generated by Django 4.2.20 on 2025-06-16 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_site_settings(apps, schema_editor) -> None:
    """Populate SiteSetting model with initial values."""
    SiteSetting = apps.get_model("recordtransfer", "SiteSetting")

    settings_data = [
        # Emails
        ("ARCHIVIST_EMAIL", "archivist@example.com", "str"),
        ("DO_NOT_REPLY_USERNAME", None, "str"),
        # Pagination
        ("PAGINATE_BY", "10", "int"),
        # CAAIS defaults
        ("CAAIS_DEFAULT_REPOSITORY", None, "str"),
        ("CAAIS_DEFAULT_ACCESSION_TITLE", None, "str"),
        ("CAAIS_DEFAULT_ARCHIVAL_UNIT", None, "str"),
        ("CAAIS_DEFAULT_DISPOSITION_AUTHORITY", None, "str"),
        ("CAAIS_DEFAULT_ACQUISITION_METHOD", None, "str"),
        ("CAAIS_DEFAULT_STATUS", None, "str"),
        ("CAAIS_DEFAULT_SOURCE_CONFIDENTIALITY", None, "str"),
        ("CAAIS_DEFAULT_PRELIMINARY_CUSTODIAL_HISTORY", None, "str"),
        ("CAAIS_DEFAULT_DATE_OF_MATERIALS", None, "str"),
        ("CAAIS_DEFAULT_EXTENT_TYPE", None, "str"),
        ("CAAIS_DEFAULT_QUANTITY_AND_UNIT_OF_MEASURE", None, "str"),
        ("CAAIS_DEFAULT_CONTENT_TYPE", None, "str"),
        ("CAAIS_DEFAULT_CARRIER_TYPE", None, "str"),
        ("CAAIS_DEFAULT_EXTENT_NOTE", None, "str"),
        ("CAAIS_DEFAULT_PRELIMINARY_SCOPE_AND_CONTENT", None, "str"),
        ("CAAIS_DEFAULT_LANGUAGE_OF_MATERIAL", None, "str"),
        ("CAAIS_DEFAULT_STORAGE_LOCATION", None, "str"),
        ("CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_TYPE", None, "str"),
        ("CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_VALUE", None, "str"),
        ("CAAIS_DEFAULT_PRESERVATION_REQUIREMENTS_NOTE", None, "str"),
        ("CAAIS_DEFAULT_APPRAISAL_TYPE", None, "str"),
        ("CAAIS_DEFAULT_APPRAISAL_VALUE", None, "str"),
        ("CAAIS_DEFAULT_APPRAISAL_NOTE", None, "str"),
        ("CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_TYPE", None, "str"),
        ("CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_TITLE", None, "str"),
        ("CAAIS_DEFAULT_ASSOCIATED_DOCUMENTATION_NOTE", None, "str"),
        ("CAAIS_DEFAULT_GENERAL_NOTE", None, "str"),
        ("CAAIS_DEFAULT_RULES_OR_CONVENTIONS", None, "str"),
        ("CAAIS_DEFAULT_LANGUAGE_OF_ACCESSION_RECORD", None, "str"),
        # CAAIS event defaults
        ("CAAIS_DEFAULT_SUBMISSION_EVENT_TYPE", None, "str"),
        ("CAAIS_DEFAULT_SUBMISSION_EVENT_AGENT", None, "str"),
        ("CAAIS_DEFAULT_SUBMISSION_EVENT_NOTE", None, "str"),
        # CAAIS creation defaults
        ("CAAIS_DEFAULT_CREATION_TYPE", None, "str"),
        ("CAAIS_DEFAULT_CREATION_AGENT", None, "str"),
        ("CAAIS_DEFAULT_CREATION_NOTE", None, "str"),
    ]

    settings_to_create = []
    for key, default_value, value_type in settings_data:
        settings_to_create.append(
            SiteSetting(
                key=key,
                value=default_value or "",
                value_type=value_type,
            )
        )

    SiteSetting.objects.bulk_create(settings_to_create)


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0050_alter_tempuploadedfile_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(editable=False, max_length=255, unique=True)),
                ("value", models.TextField()),
                (
                    "value_type",
                    models.CharField(
                        choices=[("int", "Integer"), ("str", "String")],
                        default="str",
                        editable=False,
                        max_length=8,
                        verbose_name="Setting value type",
                    ),
                ),
                (
                    "change_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Change date"),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Changed by",
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_site_settings, reverse_code=migrations.RunPython.noop),
    ]
