# Generated by Django 4.2.20 on 2025-06-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0051_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_line_1',
            field=models.CharField(help_text='Street and street number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_line_2',
            field=models.CharField(blank=True, help_text='Unit number, RPO, PO BOX (optional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(help_text='Country code', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_province_or_state',
            field=models.CharField(help_text='Other province or state if not listed', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(help_text='Phone number in format: +1 (999) 999-9999', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_or_zip_code',
            field=models.CharField(help_text='Postal code (Canada) or zip code (US)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='province_or_state',
            field=models.CharField(help_text='Province or state', max_length=64, null=True),
        ),
    ]
