# Generated by Django 4.2.20 on 2025-06-30 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0052_user_address_line_1_user_address_line_2_user_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='bag_name',
        ),
    ]
