# Generated by Django 4.2.20 on 2025-07-23 21:04

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def add_archivist_permissions(apps, schema_editor):
    """Add additional permissions to archivist_user group."""
    emit_post_migrate_signal(1, False, "default")

    group = Group.objects.get(name="archivist_user")
    existing_permissions = group.permissions.all()

    permission_specs = [
        # (app_label, model, codename)
        ("caais", "acquisitionmethod", "add_acquisitionmethod"),
        ("caais", "acquisitionmethod", "change_acquisitionmethod"),
        ("caais", "acquisitionmethod", "delete_acquisitionmethod"),
        ("caais", "acquisitionmethod", "view_acquisitionmethod"),
        ("caais", "appraisal", "add_appraisal"),
        ("caais", "appraisal", "change_appraisal"),
        ("caais", "appraisal", "delete_appraisal"),
        ("caais", "appraisal", "view_appraisal"),
        ("caais", "appraisaltype", "add_appraisaltype"),
        ("caais", "appraisaltype", "change_appraisaltype"),
        ("caais", "appraisaltype", "delete_appraisaltype"),
        ("caais", "appraisaltype", "view_appraisaltype"),
        ("caais", "archivalunit", "add_archivalunit"),
        ("caais", "archivalunit", "change_archivalunit"),
        ("caais", "archivalunit", "delete_archivalunit"),
        ("caais", "archivalunit", "view_archivalunit"),
        ("caais", "associateddocumentation", "add_associateddocumentation"),
        ("caais", "associateddocumentation", "change_associateddocumentation"),
        ("caais", "associateddocumentation", "delete_associateddocumentation"),
        ("caais", "associateddocumentation", "view_associateddocumentation"),
        ("caais", "associateddocumentationtype", "add_associateddocumentationtype"),
        ("caais", "associateddocumentationtype", "change_associateddocumentationtype"),
        ("caais", "associateddocumentationtype", "delete_associateddocumentationtype"),
        ("caais", "associateddocumentationtype", "view_associateddocumentationtype"),
        ("caais", "carriertype", "add_carriertype"),
        ("caais", "carriertype", "change_carriertype"),
        ("caais", "carriertype", "delete_carriertype"),
        ("caais", "carriertype", "view_carriertype"),
        ("caais", "contenttype", "add_contenttype"),
        ("caais", "contenttype", "change_contenttype"),
        ("caais", "contenttype", "delete_contenttype"),
        ("caais", "contenttype", "view_contenttype"),
        ("caais", "dispositionauthority", "add_dispositionauthority"),
        ("caais", "dispositionauthority", "change_dispositionauthority"),
        ("caais", "dispositionauthority", "delete_dispositionauthority"),
        ("caais", "dispositionauthority", "view_dispositionauthority"),
        ("caais", "event", "add_event"),
        ("caais", "event", "change_event"),
        ("caais", "event", "delete_event"),
        ("caais", "event", "view_event"),
        ("caais", "eventtype", "add_eventtype"),
        ("caais", "eventtype", "change_eventtype"),
        ("caais", "eventtype", "delete_eventtype"),
        ("caais", "eventtype", "view_eventtype"),
        ("caais", "extentstatement", "add_extentstatement"),
        ("caais", "extentstatement", "change_extentstatement"),
        ("caais", "extentstatement", "delete_extentstatement"),
        ("caais", "extentstatement", "view_extentstatement"),
        ("caais", "extenttype", "add_extenttype"),
        ("caais", "extenttype", "change_extenttype"),
        ("caais", "extenttype", "delete_extenttype"),
        ("caais", "extenttype", "view_extenttype"),
        ("caais", "generalnote", "add_generalnote"),
        ("caais", "generalnote", "change_generalnote"),
        ("caais", "generalnote", "delete_generalnote"),
        ("caais", "generalnote", "view_generalnote"),
        ("caais", "identifier", "add_identifier"),
        ("caais", "identifier", "change_identifier"),
        ("caais", "identifier", "delete_identifier"),
        ("caais", "identifier", "view_identifier"),
        ("caais", "languageofmaterial", "add_languageofmaterial"),
        ("caais", "languageofmaterial", "change_languageofmaterial"),
        ("caais", "languageofmaterial", "delete_languageofmaterial"),
        ("caais", "languageofmaterial", "view_languageofmaterial"),
        ("caais", "metadata", "add_metadata"),
        ("caais", "metadata", "change_metadata"),
        ("caais", "metadata", "delete_metadata"),
        ("caais", "metadata", "view_metadata"),
        ("caais", "preliminarycustodialhistory", "add_preliminarycustodialhistory"),
        ("caais", "preliminarycustodialhistory", "change_preliminarycustodialhistory"),
        ("caais", "preliminarycustodialhistory", "delete_preliminarycustodialhistory"),
        ("caais", "preliminarycustodialhistory", "view_preliminarycustodialhistory"),
        ("caais", "preliminaryscopeandcontent", "add_preliminaryscopeandcontent"),
        ("caais", "preliminaryscopeandcontent", "change_preliminaryscopeandcontent"),
        ("caais", "preliminaryscopeandcontent", "delete_preliminaryscopeandcontent"),
        ("caais", "preliminaryscopeandcontent", "view_preliminaryscopeandcontent"),
        ("caais", "preservationrequirements", "add_preservationrequirements"),
        ("caais", "preservationrequirements", "change_preservationrequirements"),
        ("caais", "preservationrequirements", "delete_preservationrequirements"),
        ("caais", "preservationrequirements", "view_preservationrequirements"),
        ("caais", "preservationrequirementstype", "add_preservationrequirementstype"),
        ("caais", "preservationrequirementstype", "change_preservationrequirementstype"),
        ("caais", "preservationrequirementstype", "delete_preservationrequirementstype"),
        ("caais", "preservationrequirementstype", "view_preservationrequirementstype"),
        ("caais", "rights", "add_rights"),
        ("caais", "rights", "change_rights"),
        ("caais", "rights", "delete_rights"),
        ("caais", "rights", "view_rights"),
        ("caais", "rightstype", "add_rightstype"),
        ("caais", "rightstype", "change_rightstype"),
        ("caais", "rightstype", "delete_rightstype"),
        ("caais", "rightstype", "view_rightstype"),
        ("caais", "sourceconfidentiality", "add_sourceconfidentiality"),
        ("caais", "sourceconfidentiality", "change_sourceconfidentiality"),
        ("caais", "sourceconfidentiality", "delete_sourceconfidentiality"),
        ("caais", "sourceconfidentiality", "view_sourceconfidentiality"),
        ("caais", "sourceofmaterial", "add_sourceofmaterial"),
        ("caais", "sourceofmaterial", "change_sourceofmaterial"),
        ("caais", "sourceofmaterial", "delete_sourceofmaterial"),
        ("caais", "sourceofmaterial", "view_sourceofmaterial"),
        ("caais", "sourcerole", "add_sourcerole"),
        ("caais", "sourcerole", "change_sourcerole"),
        ("caais", "sourcerole", "delete_sourcerole"),
        ("caais", "sourcerole", "view_sourcerole"),
        ("caais", "sourcetype", "add_sourcetype"),
        ("caais", "sourcetype", "change_sourcetype"),
        ("caais", "sourcetype", "delete_sourcetype"),
        ("caais", "sourcetype", "view_sourcetype"),
        ("caais", "status", "add_status"),
        ("caais", "status", "change_status"),
        ("caais", "status", "delete_status"),
        ("caais", "status", "view_status"),
        ("caais", "storagelocation", "add_storagelocation"),
        ("caais", "storagelocation", "change_storagelocation"),
        ("caais", "storagelocation", "delete_storagelocation"),
        ("caais", "storagelocation", "view_storagelocation"),
        ("recordtransfer", "job", "view_job"),
        ("recordtransfer", "permuploadedfile", "view_permuploadedfile"),
        ("recordtransfer", "sitesetting", "view_sitesetting"),
        ("recordtransfer", "submission", "change_submission"),
        ("recordtransfer", "submission", "view_submission"),
        ("recordtransfer", "submissiongroup", "view_submissiongroup"),
        ("recordtransfer", "tempuploadedfile", "view_tempuploadedfile"),
        ("recordtransfer", "uploadsession", "view_uploadsession"),
        ("recordtransfer", "user", "view_user"),
    ]

    for app_label, model, codename in permission_specs:
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model)
            permission = Permission.objects.get(codename=codename, content_type=content_type)
            if permission not in existing_permissions:
                group.permissions.add(permission)
        except (Permission.DoesNotExist, ContentType.DoesNotExist):
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0054_job_uuid"),
    ]

    operations = [
        migrations.RunPython(add_archivist_permissions),
    ]
