# Generated by Django 4.2.20 on 2025-08-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0055_add_archivist_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('hi', 'Hindi')], default='en', help_text='Preferred language', max_length=7, verbose_name='Preferred Language'),
        ),
    ]
