# Generated by Django 4.2.20 on 2025-07-24 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0056_user_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
    ]
