# Generated by Django 4.2.20 on 2025-08-14 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0057_add_password_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={},
        ),
    ]
