# Generated by Django 5.2.5 on 2025-08-21 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Move UploadSession, PermUploadedFile, and TempUploadedFile to upload admin."""

    dependencies = [  # noqa: RUF012
        ("recordtransfer", "0057_passwordhistory"),
        ("upload", "0001_initial"),
    ]

    operations = [  # noqa: RUF012
        # Don't remove these fields
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name="tempuploadedfile",
                    name="session",
                ),
                migrations.RemoveField(
                    model_name="uploadsession",
                    name="user",
                ),
            ],
        ),
        # Rename the PermUploadedFile table instead of deleting it
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="PermUploadedFile",
                    table="upload_permuploadedfile",
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="PermUploadedFile",
                ),
            ],
        ),
        # Rename the TempUploadedFile table instead of deleting it
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="TempUploadedFile",
                    table="upload_tempuploadedfile",
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="TempUploadedFile",
                ),
            ],
        ),
        # Rename the UploadSession table instead of deleting it
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name="UploadSession",
                    table="upload_uploadsession",
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="UploadSession",
                ),
            ],
        ),
        # Change submission upload session reference to new model
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="submission",
                    name="upload_session",
                    field=models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="upload.uploadsession",
                    ),
                ),
            ],
        ),
        # Change in-progress submission upload session reference to new model
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="inprogresssubmission",
                    name="upload_session",
                    field=models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="in_progress_submission",
                        to="upload.uploadsession",
                    ),
                ),
            ],
        ),
    ]
