# Generated by Django 5.2.13 on 2026-05-05 19:56

from django.db import migrations


from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def remove_archivist_permissions(apps, schema_editor) -> None:
    """Remove permissions from archivist_user that were moved to upload app."""
    emit_post_migrate_signal(1, False, "default")

    group, _ = Group.objects.get_or_create(name="archivist_user")
    existing_permissions = group.permissions.all()

    permission_specs = [
        # (app_label, model, codename)
        ("recordtransfer", "permuploadedfile", "view_permuploadedfile"),
        ("recordtransfer", "tempuploadedfile", "view_tempuploadedfile"),
        ("recordtransfer", "uploadsession", "view_uploadsession"),
    ]

    for app_label, model, codename in permission_specs:
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model)
            permission = Permission.objects.get(codename=codename, content_type=content_type)
            if permission in existing_permissions:
                group.permissions.remove(permission)
        except (Permission.DoesNotExist, ContentType.DoesNotExist):
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0059_remove_tempuploadedfile_session_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_archivist_permissions),
    ]
