# Generated by Django 5.2.13 on 2026-05-05 20:35

from django.db import migrations, models


def delete_in_progress_submissions(apps, schema_editor):
    """Delete all existing InProgressSubmission rows.

    The previous step_data field was a BinaryField containing pickled data.
    Rather than unpickling untrusted binary data to convert it to JSON, we
    delete all in-progress submissions before altering the field type.
    """
    InProgressSubmission = apps.get_model("recordtransfer", "InProgressSubmission")
    InProgressSubmission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0060_remove_upload_permissions_from_archivist'),
    ]

    operations = [
        migrations.RunPython(
            delete_in_progress_submissions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='inprogresssubmission',
            name='step_data',
            field=models.JSONField(default=dict),
        ),
    ]
