# Generated by Django 5.2.13 on 2026-05-05 20:49

from django.db import migrations, models

# Sentinel value written to raw_form for Submissions that existed before
# raw_form was converted from a pickled BinaryField to a JSONField. The
# original pickled bytes are discarded rather than unpickled.
LEGACY_RAW_FORM_SENTINEL = {
    "message": (
        "This Submission was created before raw_form was converted from "
        "a pickled binary field to JSON. The original form data is not "
        "available."
    )
}


def clear_pickled_raw_form(apps, schema_editor):
    """Clear existing pickled raw_form bytes before converting to JSON.

    MySQL cannot convert binary string values directly to JSON because the
    source values have CHARACTER SET 'binary'. Setting the column to NULL first
    avoids converting any binary values. The sentinel is written after raw_form
    has been converted to a JSONField.
    """
    Submission = apps.get_model("recordtransfer", "Submission")
    Submission.objects.all().update(raw_form=None)


def write_legacy_raw_form_sentinel(apps, schema_editor):
    """Write the legacy sentinel after raw_form has become a JSONField."""
    Submission = apps.get_model("recordtransfer", "Submission")
    Submission.objects.all().update(raw_form=LEGACY_RAW_FORM_SENTINEL)


class Migration(migrations.Migration):
    dependencies = [
        ("recordtransfer", "0061_alter_inprogresssubmission_step_data"),
    ]

    operations = [
        migrations.RunPython(
            clear_pickled_raw_form,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="submission",
            name="raw_form",
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.RunPython(
            write_legacy_raw_form_sentinel,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="submission",
            name="raw_form",
            field=models.JSONField(default=dict),
        ),
    ]
