# Generated by Django 5.2.13 on 2026-05-05 20:49

import json

from django.db import migrations, models

# Sentinel value written to raw_form for Submissions that existed before
# raw_form was converted from a pickled BinaryField to a JSONField. The
# original pickled bytes are discarded rather than unpickled.
LEGACY_RAW_FORM_SENTINEL = {
    "message": (
        "This Submission was created before raw_form was converted from "
        "a pickled binary field to JSON. The original form data is not "
        "available."
    )
}


def replace_pickled_raw_form(apps, schema_editor):
    """Overwrite existing pickled raw_form bytes with the JSON-encoded sentinel.

    This runs while raw_form is still a BinaryField so that, after the
    AlterField to JSONField, the column contains valid JSON for every row.
    """
    Submission = apps.get_model("recordtransfer", "Submission")
    sentinel_bytes = json.dumps(LEGACY_RAW_FORM_SENTINEL).encode("utf-8")
    Submission.objects.all().update(raw_form=sentinel_bytes)


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0061_alter_inprogresssubmission_step_data'),
    ]

    operations = [
        migrations.RunPython(
            replace_pickled_raw_form,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='submission',
            name='raw_form',
            field=models.JSONField(default=dict),
        ),
    ]
