# Generated by Django 3.2.11 on 2022-03-29 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='This element is intended to support the tracking of a material through an accession procedure that has clearly defined, successive phases', max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(help_text="Give the authorized form(s) of the name of the institution in accordance with the repository's naming standard", max_length=128, null=True)),
                ('accession_title', models.CharField(help_text="Supply an accession title in accordance with the repository's descriptive standard, typically consisting of the creator's name(s) and the type of material", max_length=128, null=True)),
                ('acquisition_method', models.CharField(help_text='Record the acquisition method in accordance with a controlled vocabulary', max_length=128, null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metadatas', to='caais.status')),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(help_text='Record the identifier type in accordance with a controlled vocabulary maintained by the repository', max_length=128)),
                ('identifier_value', models.CharField(help_text='Record the other identifier value as received or generated by the repository', max_length=128)),
                ('identifier_note', models.TextField(help_text='Record any additional information that clarifies the purpose, use or generation of the identifier.', null=True)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='caais.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='DispositionAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition_authority', models.TextField(help_text='Record information about any legal instruments that apply to the accessioned material. Legal instruments include statutes, records schedules or disposition authorities, and donor agreements')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_authorities', to='caais.metadata')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archival_unit', models.TextField(help_text='Record the reference code and/or title of the archival unit to which the accession belongs')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archival_units', to='caais.metadata')),
            ],
        ),
    ]
