# Generated by Django 3.2.11 on 2022-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0003_caais_section_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='date_of_material',
            field=models.CharField(help_text='Provide a preliminary estimate of the date range or explicitly indicate if not it has yet been determined', max_length=128, null=True),
        ),
    ]
