# Generated by Django 3.2.11 on 2022-11-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0009_preservationassessment_preservationassessmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivalunit',
            name='archival_unit',
            field=models.TextField(help_text='Record the reference code and/or title of the archival unit to which the accession belongs.'),
        ),
    ]
