# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for detail

version: 2

build:
  os: "ubuntu-22.04"
  commands:
    - apt install pipx
    - pipx ensurepath
    - pipx install --user poetry
    - poetry config virtualenvs.create false
    - poetry install --extras docs
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
