# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for detail
#
# This configuration uses poetry to install dependencies because pip has trouble handling
# package-mode = false in the pyproject.toml file.

version: 2

build:
  os: "ubuntu-22.04"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false

    post_install:
      - . "$READTHEDOCS_VIRTUALENV_PATH/bin/activate" && poetry install --extras docs

  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py
