services:
  clamav:
    image: docker.io/clamav/clamav
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:z
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:z
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:z
    environment:
      REDIS_REPLICATION_MODE: master

  # See: https://mailpit.axllent.org/docs/install/docker/
  email:
    image: docker.io/axllent/mailpit:latest
    container_name: recordtransfer_mailpit
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    volumes:
      - mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  rq:
    build:
      context: .
      dockerfile: Containerfile
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    volumes:
      - ./bagitobjecttransfer/:/app/bagitobjecttransfer/:z
      - temp-directory:/tmp
    ports:
      - 8010:8010
    env_file:
      - .dev.env
    # See manage.py for debugger setup
    environment:
      - ENV=dev
      - IS_RQ=yes
      - ENABLE_DEBUGPY=1
      - ENABLE_DEBUGPY_ON_COMMAND=rqworker
      - DEBUGPY_PORT=8010
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: recordtransfer_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bagitobjecttransfer/:/app/bagitobjecttransfer/:z
      - temp-directory:/tmp
    ports:
      - 8000:8000
      - 8009:8009
    env_file:
      - .dev.env
    # See manage.py for debugger setup
    environment:
      - ENV=dev
      - IS_RQ=no
      - ENABLE_DEBUGPY=1
      - ENABLE_DEBUGPY_ON_COMMAND=runserver
      - DEBUGPY_PORT=8009
    depends_on:
      - rq
      - email
      - clamav

volumes:
  temp-directory:
  clamav-virusdb:
  mailpit-data:
