version: "3.8"

services:
  clamav:
    image: docker.io/clamav/clamav
    restart: unless-stopped
    networks:
      - clamav-net
    volumes:
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:z
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:z

  redis:
    image: docker.io/redis:7-alpine
    command: /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 1m00s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - redis-net
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:z
    environment:
      REDIS_REPLICATION_MODE: master

  db:
    image: docker.io/mysql:8
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1m00s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - db-net
    env_file:
      - .prod.env
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql:z
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:z

  rq:
    build:
      context: .
      dockerfile: Containerfile
    command: python manage.py rqworker default
    restart: unless-stopped
    networks:
      - db-net
      - redis-net
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - IS_RQ=yes
    depends_on:
      - db
      - redis

  app:
    build:
      context: .
      dockerfile: Containerfile
    command: gunicorn bagitobjecttransfer.wsgi:application --bind 0.0.0.0:8000 --enable-stdio-inheritance
    restart: unless-stopped
    networks:
      - clamav-net
      - db-net
      - frontend-net
    expose:
      - 8000
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - IS_RQ=no
    depends_on:
      - db
      - rq
      - clamav
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/

  nginx:
    image: docker.io/nginx:stable
    restart: unless-stopped
    networks:
      - frontend-net
    ports:
      - 1337:81
    depends_on:
      - app
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:z

volumes:
  mysql-database:
  static-volume:
  media-volume:
  temp-directory:
  clamav-virusdb:

networks:
  clamav-net:
  db-net:
  redis-net:
  frontend-net:
