services:
  clamav:
    image: docker.io/clamav/clamav-debian
    restart: unless-stopped
    volumes:
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:z
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:z

  redis:
    image: docker.io/redis:7-alpine
    command: /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    healthcheck:
      test: redis-cli --raw incr ping
      interval: 1m00s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:z
    environment:
      REDIS_REPLICATION_MODE: master

  db:
    image: docker.io/mysql:8
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf
    restart: unless-stopped
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1m00s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .prod.env
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql:z
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:z

  rq:

    image: secure-record-transfer-prod
    command: python manage.py rqworker default
    restart: unless-stopped
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - SERVICE_NAME=rq
      - DJANGO_SETTINGS_MODULE=app.settings.docker_prod
    depends_on:
      - db
      - redis
    volumes:
      - static-volume:/opt/secure-record-transfer/app/static/
      - media-volume:/opt/secure-record-transfer/app/media/

  rq-scheduler:
    image: secure-record-transfer-prod
    command: python manage.py schedule_jobs
    restart: unless-stopped
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - SERVICE_NAME=rq-scheduler
      - DJANGO_SETTINGS_MODULE=app.settings.docker_prod
    depends_on:
      - rq

  app:
    image: secure-record-transfer-prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --enable-stdio-inheritance
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - SERVICE_NAME=app
      - DJANGO_SETTINGS_MODULE=app.settings.docker_prod
    depends_on:
      - rq
      - rq-scheduler
      - clamav
    volumes:
      - static-volume:/opt/secure-record-transfer/app/static/
      - media-volume:/opt/secure-record-transfer/app/media/

  nginx:
    image: docker.io/nginx:stable
    restart: unless-stopped
    ports:
      - 1337:81
    depends_on:
      - app
    volumes:
      - static-volume:/opt/secure-record-transfer/static/
      - media-volume:/opt/secure-record-transfer/media/
      - ./docker/nginx/templates/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:z
      - ./app/templates/:/var/www/html/:z
    env_file:
      - .prod.env
    environment:
      - STATIC_ROOT=/opt/secure-record-transfer/static/
      - MEDIA_ROOT=/opt/secure-record-transfer/media/

volumes:
  mysql-database:
  static-volume:
  media-volume:
  temp-directory:
  clamav-virusdb:
