# Generated by Django 3.2.11 on 2022-04-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispositionauthority',
            options={'verbose_name': 'Disposition authority', 'verbose_name_plural': 'Disposition authorities'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'CAAIS metadata', 'verbose_name_plural': 'CAAIS metadata'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Accession status', 'verbose_name_plural': 'Accession statuses'},
        ),
    ]
