# Generated by Django 3.2.11 on 2022-04-14 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0004_auto_20220413_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record the physical format of an object that supports or carries archival materials using a controlled vocabulary maintained by the repository', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Content type',
                'verbose_name_plural': 'Carrier types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record the type of material contained in the units measured, i.e., the <b>genre</b> of the material', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Content type',
                'verbose_name_plural': 'Content types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record the extent statement type in accordance with a controlled vocabulary maintained by the repository', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Extent type',
                'verbose_name_plural': 'Extent types',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sourceconfidentiality',
            name='source_confidentiality',
        ),
        migrations.RemoveField(
            model_name='sourcerole',
            name='source_role',
        ),
        migrations.RemoveField(
            model_name='sourcetype',
            name='source_type',
        ),
        migrations.RemoveField(
            model_name='status',
            name='status',
        ),
        migrations.AddField(
            model_name='sourceconfidentiality',
            name='name',
            field=models.CharField(default='N/A', help_text='Record source statements or source information that is for internal use only by the repository. Repositories should develop a controlled vocabulary with terms that can be translated into clear rules for handling source information', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcerole',
            name='name',
            field=models.CharField(default='N/A', help_text='Record the source role (when known) in accordance with a controlled vocabulary maintained by the repository', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sourcetype',
            name='name',
            field=models.CharField(default='N/A', help_text='Record the source in accordance with a controlled vocabulary maintained by the repository', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='name',
            field=models.CharField(default='N/A', help_text="Record the current position of the material with respect to the repository's workflows and business processes using a controlled vocabulary", max_length=128),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PreliminaryScopeAndContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preliminary_scope_and_content', models.TextField(help_text="Record a preliminary description that may include: functions and activities that resulted in the material's generation, dates, the geographic area to which the material pertains, subject matter, arrangement, classification, and documentary forms")),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_scope_and_contents', to='caais.metadata')),
            ],
            options={
                'verbose_name': 'Preliminary scope and content',
                'verbose_name_plural': 'Preliminary scope and contents',
            },
        ),
        migrations.CreateModel(
            name='LanguageOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_of_material', models.CharField(help_text='Record, at a minimum, the language that is predominantly found in the accessioned material', max_length=128)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_of_materials', to='caais.metadata')),
            ],
            options={
                'verbose_name': 'Language of material',
                'verbose_name_plural': 'Language of materials',
            },
        ),
        migrations.CreateModel(
            name='ExtentStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_and_unit_of_measure', models.CharField(default='Not specified', help_text='Record the number and unit of measure expressing the quantity of the extent (e.g., 5 files, totalling 2.5MB)', max_length=256)),
                ('extent_note', models.TextField(blank=True, default='', help_text='Record additional information related to the number and type of units received, retained, or removed not otherwise recorded')),
                ('carrier_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.carriertype')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.contenttype')),
                ('extent_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.extenttype')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extent_statements', to='caais.metadata')),
            ],
            options={
                'verbose_name': 'Extent statement',
                'verbose_name_plural': 'Extent statements',
            },
        ),
    ]
