# Generated by Django 3.2.11 on 2022-04-14 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0006_extent_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='RightsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Record the rights statement type in accordance with a controlled vocabulary maintained by the repository', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Rights',
                'verbose_name_plural': 'Rights types',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location', models.TextField(help_text='Record the physical and/or digital location(s) within the repository in which the accessioned material is stored')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='caais.metadata')),
            ],
            options={
                'verbose_name': 'Storage location',
                'verbose_name_plural': 'Storage locations',
            },
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rights_value', models.TextField(blank=True, default='', help_text='Record the nature and duration of the permission granted or restriction imposed. Specify where the condition applies only to part of the accession')),
                ('rights_note', models.TextField(blank=True, default='', help_text='Record any other information relevant to describing the rights statement')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='caais.metadata')),
                ('rights_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_type', to='caais.rightstype')),
            ],
            options={
                'verbose_name': 'Rights',
                'verbose_name_plural': 'Rights',
            },
        ),
    ]
