# Generated by Django 4.2.19 on 2025-03-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0012_auto_20230927_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='date_is_approximate',
            field=models.BooleanField(default=False, help_text='Date is approximated'),
        ),
    ]
