# Generated by Django 4.2.19 on 2025-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('caais', '0013_metadata_date_is_approximate'), ('caais', '0014_alter_metadata_date_is_approximate')]

    dependencies = [
        ('caais', '0012_auto_20230927_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='date_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
