# Generated by Django 4.2.19 on 2025-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0013_metadata_date_is_approximate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='date_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
