# Generated by Django 5.2.5 on 2025-10-21 17:31

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0013_metadata_date_is_approximate_squashed_0014_alter_metadata_date_is_approximate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='associateddocumentation',
            options={'verbose_name': 'Associated documentation', 'verbose_name_plural': 'Associated documentation'},
        ),
        migrations.AlterModelOptions(
            name='creationorrevisiontype',
            options={'verbose_name': 'Creation or revision type', 'verbose_name_plural': 'Creation or revision types'},
        ),
        migrations.AlterModelOptions(
            name='rightstype',
            options={'verbose_name': 'Rights type', 'verbose_name_plural': 'Rights types'},
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information relevant to describing the appraisal activities. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.4.3]', verbose_name='Appraisal note'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisals', to='caais.appraisaltype', verbose_name='Appraisal type'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='appraisal_value',
            field=models.TextField(blank=True, default='', help_text='Where the accession process includes appraisal activities, record the appraisal statement value. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.4.2]', verbose_name='Appraisal value'),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='archival_unit',
            field=models.TextField(help_text='Record the reference code and/or title of the archival unit to which the accession belongs [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.4]', verbose_name='Archival unit'),
        ),
        migrations.AlterField(
            model_name='archivalunit',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archival_units', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='associateddocumentation',
            name='associated_documentation_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information relevant to describing documentation associated to the accessioned material [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.5.3]', verbose_name='Associated documentation note'),
        ),
        migrations.AlterField(
            model_name='associateddocumentation',
            name='associated_documentation_title',
            field=models.TextField(blank=True, default='', help_text='Record the title of the associated documentation [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.5.2]', verbose_name='Associated documentation title'),
        ),
        migrations.AlterField(
            model_name='associateddocumentation',
            name='associated_documentation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_documentation', to='caais.associateddocumentationtype', verbose_name='Associated documentation type'),
        ),
        migrations.AlterField(
            model_name='associateddocumentation',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_documentation', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='dateofcreationorrevision',
            name='creation_or_revision_agent',
            field=models.CharField(blank=True, default='', help_text='Record the name of the staff member who performed the action (creation or revision) on the accession record [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 7.2.3]', max_length=256, verbose_name='Creation or revision agent'),
        ),
        migrations.AlterField(
            model_name='dateofcreationorrevision',
            name='creation_or_revision_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation or revision note'),
        ),
        migrations.AlterField(
            model_name='dateofcreationorrevision',
            name='creation_or_revision_note',
            field=models.TextField(blank=True, default='', help_text='Record any information summarizing actions applied to the accession record. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 7.2.4]', verbose_name='Creation or revision note'),
        ),
        migrations.AlterField(
            model_name='dateofcreationorrevision',
            name='creation_or_revision_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dates_of_creation_or_revision', to='caais.creationorrevisiontype', verbose_name='Creation or revision type'),
        ),
        migrations.AlterField(
            model_name='dateofcreationorrevision',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_of_creation_or_revision', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='dispositionauthority',
            name='disposition_authority',
            field=models.TextField(help_text='Record information about any legal instruments that apply to the accessioned material. Legal instruments include statutes, records schedules or disposition authorities, and donor agreements [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.6]', verbose_name='Disposition authority'),
        ),
        migrations.AlterField(
            model_name='dispositionauthority',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposition_authorities', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_agent',
            field=models.CharField(blank=True, default='', help_text='Record the name of the staff member or application responsible for the event [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 5.1.3]', max_length=256, verbose_name='Event agent'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information relevant to describing the event. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 5.1.4]', verbose_name='Event note'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_type', to='caais.eventtype', verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='carrier_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.carriertype', verbose_name='Carrier type'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.contenttype', verbose_name='Content type'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='extent_note',
            field=models.TextField(blank=True, default='', help_text='Record additional information related to the number and type of units received, retained, or removed not otherwise recorded [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 3.2.5]', verbose_name='Extent note'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='extent_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extent_statements', to='caais.extenttype', verbose_name='Extent type'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extent_statements', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='extentstatement',
            name='quantity_and_unit_of_measure',
            field=models.TextField(blank=True, default='', help_text='Record the number and unit of measure expressing the quantity of the extent (e.g., 5 files, totalling 2.5MB) [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 3.2.2]', verbose_name='Quantity and unit of measure'),
        ),
        migrations.AlterField(
            model_name='generalnote',
            name='general_note',
            field=models.TextField(help_text='Record any other information relevant to the accession record or accessioning process [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 6.1]', verbose_name='General note'),
        ),
        migrations.AlterField(
            model_name='generalnote',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_notes', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier_note',
            field=models.TextField(blank=True, default='', help_text='Record any additional information that clarifies the purpose, use or generation of the identifier. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.2.3]', verbose_name='Identifier note'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier_type',
            field=models.CharField(blank=True, default='', help_text='Record the identifier type in accordance with a controlled vocabulary maintained by the repository [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.2.1]', max_length=128, verbose_name='Identifier type'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='identifier_value',
            field=models.CharField(help_text='Record the other identifier value as received or generated by the repository [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.2.2]', max_length=128, verbose_name='Identifier type'),
        ),
        migrations.AlterField(
            model_name='identifier',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='languageofmaterial',
            name='language_of_material',
            field=models.TextField(help_text='Record, at a minimum, the language that is predominantly found in the accessioned material [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 3.4]', verbose_name='Language of material'),
        ),
        migrations.AlterField(
            model_name='languageofmaterial',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_of_materials', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='accession_title',
            field=models.CharField(blank=True, default='', help_text='Supply an accession title in accordance with the repository\'s descriptive standard, typically consisting of the creator\'s name(s) and the type of material [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.3]', max_length=512, verbose_name='Accession title'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='acquisition_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caais.acquisitionmethod', verbose_name='Acquisition method'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='date_is_approximate',
            field=models.BooleanField(default=False, verbose_name='Date is approximate'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='date_of_materials',
            field=models.CharField(blank=True, default='', help_text='Provide a preliminary estimate of the date range or explicitly indicate if not it has yet been determined [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 3.1]', max_length=512, verbose_name='Date of materials'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='language_of_accession_record',
            field=models.CharField(blank=True, default='en', help_text='Record the language(s) and script(s) used to create the accession record. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 7.3]', max_length=256, verbose_name='Language of accession record'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='repository',
            field=models.CharField(blank=True, default='', help_text='Give the authorized form(s) of the name of the institution in accordance with the repository\'s naming standard [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 1.1]', max_length=512, verbose_name='Repository'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='rules_or_conventions',
            field=models.CharField(blank=True, default='', help_text='Record information about the standards, rules or conventions that were followed when creating or maintaining the accession record. [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 7.1]', max_length=256, verbose_name='Rules or conventions'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caais.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='preliminarycustodialhistory',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_custodial_histories', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='preliminarycustodialhistory',
            name='preliminary_custodial_history',
            field=models.TextField(help_text='Provide relevant custodial history information in accordance with the repository\'s descriptive standard. Record the successive transfers of ownership, responsibility and/or custody of the accessioned material prior to its transfer to the repository [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 2.2]', verbose_name='Preliminary custodial history'),
        ),
        migrations.AlterField(
            model_name='preliminaryscopeandcontent',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preliminary_scope_and_contents', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='preliminaryscopeandcontent',
            name='preliminary_scope_and_content',
            field=models.TextField(help_text='Record a preliminary description that may include: functions and activities that resulted in the material\'s generation, dates, the geographic area to which the material pertains, subject matter, arrangement, classification, and documentary forms [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 3.3]', verbose_name='Preliminary scope and content'),
        ),
        migrations.AlterField(
            model_name='preservationrequirements',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preservation_requirements', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='preservationrequirements',
            name='preservation_requirements_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information relevant to the long-term preservation of the material [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.3.3]', verbose_name='Preservation requirements note'),
        ),
        migrations.AlterField(
            model_name='preservationrequirements',
            name='preservation_requirements_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preservation_requirements', to='caais.preservationrequirementstype', verbose_name='Preservation requirements type'),
        ),
        migrations.AlterField(
            model_name='preservationrequirements',
            name='preservation_requirements_value',
            field=models.TextField(blank=True, default='', help_text='Record information about the assessment of the material with respect to its physical condition, dependencies, processing or access [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.3.2]', verbose_name='Preservation requirements value'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='rights_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information relevant to describing the rights statement [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.2.3]', verbose_name='Rights note'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='rights_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rights_type', to='caais.rightstype', verbose_name='Rights type'),
        ),
        migrations.AlterField(
            model_name='rights',
            name='rights_value',
            field=models.TextField(blank=True, default='', help_text='Record the nature and duration of the permission granted or restriction imposed. Specify where the condition applies only to part of the accession [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.2.2]', verbose_name='Rights value'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='address_line_1',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Address line 1'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='address_line_2',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Address line 2'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='city',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='email_address',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Job title'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_materials', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='postal_or_zip_code',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Postal or zip code'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='region',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='source_confidentiality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_of_materials', to='caais.sourceconfidentiality', verbose_name='Source confidentiality'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='source_name',
            field=models.CharField(blank=True, default='', help_text='Record the source name in accordance with the repository\'s descriptive standard [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 2.1.2]', max_length=256, verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='source_note',
            field=models.TextField(blank=True, default='', help_text='Record any other information about the source of the accessioned materials. If the source performed the role for only a specific period of time (e.g. was a custodian for several years), record the dates in this element [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 2.1.5]', verbose_name='Source name'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='source_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_of_materials', to='caais.sourcerole', verbose_name='Source role'),
        ),
        migrations.AlterField(
            model_name='sourceofmaterial',
            name='source_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_of_materials', to='caais.sourcetype', verbose_name='Source type'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locations', to='caais.metadata', verbose_name='CAAIS metadata'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='storage_location',
            field=models.TextField(help_text='Record the physical and/or digital location(s) within the repository in which the accessioned material is stored [<a href="https://archivescanada.ca/wp-content/uploads/2022/12/CAAIS_2019May15_EN.pdf" target="_blank">CAAIS</a> 4.1]', verbose_name='Storage location'),
        ),
    ]
