version: "3.8"

services:
  clamav:
    image: docker.io/clamav/clamav
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      REDIS_REPLICATION_MODE: master

  email:
    image: docker.io/mailhog/mailhog
    user: root
    container_name: recordtransfer_mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: '/home/mailhog/mail'
    volumes:
      - mailhog:/home/mailhog/mail

  rq:
    build:
      context: .
      dockerfile: Containerfile
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    volumes:
      - ./:/app
      - temp-directory:/tmp
    ports:
      - 8010:8010
    env_file:
      - .dev.env
    # See manage.py for debugger setup
    environment:
      - ENV=dev
      - IS_RQ=yes
      - ENABLE_DEBUGPY=1
      - ENABLE_DEBUGPY_ON_COMMAND=rqworker
      - DEBUGPY_PORT=8010
    depends_on:
      - redis

  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: recordtransfer_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - temp-directory:/tmp
    ports:
      - 8000:8000
      - 8009:8009
    env_file:
      - .dev.env
    # See manage.py for debugger setup
    environment:
      - ENV=dev
      - IS_RQ=no
      - ENABLE_DEBUGPY=1
      - ENABLE_DEBUGPY_ON_COMMAND=runserver
      - DEBUGPY_PORT=8009
    depends_on:
      - rq
      - email
      - clamav

volumes:
  temp-directory:
  clamav-virusdb:
  mailhog:
