version: "3.8"

services:
  clamav:
    image: docker.io/clamav/clamav
    container_name: recordtransfer_clamav
    volumes:
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro

  redis:
    image: docker.io/redis:7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      REDIS_REPLICATION_MODE: master

  db:
    image: docker.io/mysql:8
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    env_file:
      - .prod.env
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/logs/mysql:/var/log/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - IS_RQ=yes
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
      - redis

  app:
    build: .
    container_name: recordtransfer_django_app
    command: gunicorn bagitobjecttransfer.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    expose:
      - 8000
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - IS_RQ=no
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
      - rq
      - clamav
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/

  nginx:
    image: docker.io/nginx:stable
    restart: unless-stopped
    ports:
      - 1337:81
    depends_on:
      - app
    links:
      - app
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

volumes:
  mysql-database:
  static-volume:
  media-volume:
  temp-directory:
  clamav-virusdb:
