FROM python:3.10

# Set Work Directoy
WORKDIR /app

# Set Environment Variables
ENV PYTHONUNBUFFERED=1

# Copy app files
COPY . .

# Make directories, install dependencies and prepare entrypoint script
RUN pip install --upgrade setuptools wheel \
    && pip install -r requirements.txt \
    && apt-get install -y curl \
    && curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh | bash - \
    && apt-get install -y nodejs \
    && npm install -g npm \
    && npm install \
    && sed -i 's/\r$//g' /app/docker/entrypoint.sh \
    && chmod +x /app/docker/entrypoint.sh

ENTRYPOINT ["/app/docker/entrypoint.sh"]
