version: "3.8"

services:
  db:
    image: mysql
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
    env_file:
      - ./.dockerenv
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql

  email:
    image: mailhog/mailhog
    user: root
    container_name: recordtransfer_mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: '/home/mailhog/mail'
    volumes:
      - mailhog:/home/mailhog/mail

  app:
    build: .
    container_name: recordtransfer_django_app
    entrypoint:
      - /bin/bash
      - /app/docker/django/django-entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    ports:
      - 8000:8000
    env_file:
      - ./.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
    depends_on:
      - rq
      - db
      - email

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    entrypoint:
      - /bin/bash
      - /app/docker/django-rq/django-rq-entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    env_file:
      - ./.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
    depends_on:
      - db
      - redis

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/logs/redis:/var/log/redis
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  temp-directory:
  mysql-database:
  mailhog:
