version: "3.8"

services:
  db:
    image: mysql
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .prod.env
    volumes:
      - mysql-database-prod:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: recordtransfer_django_app
    command: gunicorn bagitobjecttransfer.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .prod.env
    depends_on:
      - db
      - rq
      - clamav

  rq:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis

volumes:
  mysql-database-prod:
