version: "3.8"

services:
  db:
    image: mysql:8
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .prod.env
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
      - redis

  app:
    build: .
    container_name: recordtransfer_django_app
    command: gunicorn bagitobjecttransfer.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - .prod.env
    environment:
      - ENV=prod
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
      - rq
      - clamav
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/

  nginx:
    build: ./docker/nginx
    ports:
      - 1337:80
    depends_on:
      - app
    volumes:
      - static-volume:/app/static/
      - media-volume:/app/media/

volumes:
  mysql-database:
  static-volume:
  media-volume:
