version: "3.8"

services:
  db:
    image: mysql
    container_name: recordtransfer_mysqldb
    restart: always
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
    env_file:
      - ./.dockerenv
    volumes:
      - mysql-database:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/mysqld.cnf
      - ./logs:/var/log/mysql

  app:
    build: .
    container_name: recordtransfer_django_app
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=bagitobjecttransfer.settings.docker
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./logs/rqworker.log:/var/log/django-rq/rqworker.log
      - ./logs/recordtransfer.log:/var/log/django/recordtransfer.log
    ports:
      - 8000:8000
    env_file:
      - ./.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
    depends_on:
      - rq
      - db

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    command: python3 manage.py rqworker default
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./logs/rqworker.log:/var/log/django-rq/rqworker.log
      - ./logs/recordtransfer.log:/var/log/django/recordtransfer.log
    env_file:
      - ./.dockerenv
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
    depends_on:
      - redis

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_server
    command: sh -c "touch /var/log/redis/redis-server.log && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./logs/redis-server.log:/var/log/redis/redis-server.log
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  temp-directory:
  mysql-database:
