version: "3.8"

# These services are not unique - i.e., they are used by both the development
# and production Docker configurations
services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/logs/clamav:/var/log/clamav
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  redis:
    image: redis:7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/logs/redis:/var/log/redis
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  temp-directory:
  clamav-virusdb:
