version: "3.8"

services:
  db:
    image: mysql
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    healthcheck:
      test: ["CMD", "mysqladmin", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "ping", "-h", "localhost"]
      interval: 8s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql

  email:
    image: mailhog/mailhog
    user: root
    container_name: recordtransfer_mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: '/home/mailhog/mail'
    volumes:
      - mailhog:/home/mailhog/mail

  clamav:
    image: mkodockx/docker-clamav:1.0.9-alpine
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/logs/clamav:/var/log/clamav
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  app:
    build: .
    container_name: recordtransfer_django_app
    entrypoint:
      - /bin/bash
      - /app/docker/django/django-entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    ports:
      - 8000:8000
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
      SIGN_UP_ENABLED: ${SIGN_UP_ENABLED}
      ALLOW_BAG_CHANGES: ${ALLOW_BAG_CHANGES}
      BAG_STORAGE_FOLDER: ${BAG_STORAGE_FOLDER}
      UPLOAD_STORAGE_FOLDER: ${UPLOAD_STORAGE_FOLDER}
      ARCHIVIST_EMAIL: ${ARCHIVIST_EMAIL}
    depends_on:
      db:
        condition: service_healthy
      rq:
        condition: service_started
      email:
        condition: service_started
      clamav:
        condition: service_started

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    entrypoint:
      - /bin/bash
      - /app/docker/django-rq/django-rq-entrypoint.sh
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    environment:
      DJANGO_SETTINGS_MODULE: bagitobjecttransfer.settings.docker
      SIGN_UP_ENABLED: ${SIGN_UP_ENABLED}
      ALLOW_BAG_CHANGES: ${ALLOW_BAG_CHANGES}
      BAG_STORAGE_FOLDER: ${BAG_STORAGE_FOLDER}
      UPLOAD_STORAGE_FOLDER: ${UPLOAD_STORAGE_FOLDER}
      ARCHIVIST_EMAIL: ${ARCHIVIST_EMAIL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 8s
      timeout: 10s
      retries: 3
      start_period: 5s
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/logs/redis:/var/log/redis
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  temp-directory:
  mysql-database:
  mailhog:
  clamav-virusdb:
