version: "3.8"

services:
  db:
    image: mysql
    container_name: recordtransfer_mysqldb
    command: --defaults-extra-file=/etc/mysql/mysqld.cnf --default-authentication-plugin=mysql_native_password --mysqlx=0
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql-database:/var/lib/mysql
      - ./docker/mysql/mysqld.cnf:/etc/mysql/mysqld.cnf:ro
      - ./docker/logs/mysql:/var/log/mysql

  email:
    image: mailhog/mailhog
    user: root
    container_name: recordtransfer_mailhog
    logging:
      driver: 'none' # disable saving logs
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: '/home/mailhog/mail'
    volumes:
      - mailhog:/home/mailhog/mail

  clamav:
    image: mkodockx/docker-clamav:1.0.9-alpine
    container_name: recordtransfer_clamav
    ports:
      - 3310:3310
    volumes:
      - ./docker/logs/clamav:/var/log/clamav
      - ./docker/clamav/clamd.conf:/etc/clamav/clamd.conf:ro
      - ./docker/clamav/freshclam.conf:/etc/clamav/freshclam.conf:ro
      - clamav-virusdb:/var/lib/clamav
      - temp-directory:/tmp

  app:
    build: .
    container_name: recordtransfer_django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - rq
      - email
      - clamav

  rq:
    build: .
    container_name: recordtransfer_rq_workers
    command: python manage.py rqworker default
    volumes:
      - ./:/app
      - temp-directory:/tmp
      - ./docker/logs/django-rq:/var/log/django-rq/
      - ./docker/logs/django:/var/log/django/
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:5.0.7-alpine
    container_name: redis_server
    command: /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./docker/logs/redis:/var/log/redis
    environment:
      REDIS_REPLICATION_MODE: master

volumes:
  temp-directory:
  mysql-database:
  mailhog:
  clamav-virusdb:
