# Generated by Django 3.0.4 on 2020-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='password_sha_512',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='bag',
            name='report',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_location',
            field=models.TextField(),
        ),
    ]
