# Generated by Django 3.0.4 on 2020-09-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recordtransfer', '0002_auto_20200901_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
