# Generated by Django 3.0.4 on 2020-09-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0003_auto_20200901_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='report',
        ),
        migrations.AddField(
            model_name='bag',
            name='report_location',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_location',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
