# Generated by Django 3.0.4 on 2020-09-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0004_auto_20200901_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='review_status',
            field=models.CharField(choices=[('NR', 'Not Reviewed'), ('RS', 'Review Started'), ('RC', 'Review Complete')], default='NR', max_length=2),
        ),
    ]
