# Generated by Django 3.0.4 on 2020-09-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0006_auto_20200902_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='report_contents',
            field=models.TextField(default='<p>This report does not exist.</p>'),
        ),
    ]
