# Generated by Django 3.1.1 on 2020-09-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0007_bag_report_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='report_name',
        ),
    ]
