# Generated by Django 3.1.1 on 2020-11-23 16:06
# Modified by Daniel Lovegrove

from django.db import migrations
from django.contrib.sites.models import Site


def update_local_site(apps, schema_editor):
    local_domain = '127.0.0.1:8000'

    Site.objects.update_or_create(
        pk=1,
        defaults={
            'domain': local_domain,
            'name': 'Record Transfer'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),

    ]

    operations = [
        migrations.RunPython(update_local_site),
    ]

