# Generated by Django 3.1.8 on 2021-05-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0014_auto_20210513_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='right',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
