# Generated by Django 3.1.8 on 2021-09-09 15:24

from django.db import migrations, models
from django.core.management.sql import emit_post_migrate_signal
from django.contrib.auth.models import Group, Permission
from recordtransfer.models import SourceType, SourceRole


def populate_initial_terms(apps, schema_editor):
    other_type, created = SourceType.objects.get_or_create(
        name='Other',
        description='Placeholder right to allow user to specify unique source type'
    )
    if created:
        other_type.save()

    other_role, created = SourceRole.objects.get_or_create(
        name='Other',
        description='Placeholder right to allow user to specify unique source role'
    )
    if created:
        other_role.save()


def populate_permissions(apps, schema_editor):
    ''' Add term permissions for archival staff '''
    emit_post_migrate_signal(1, False, 'default')
    group = Group.objects.get(name='archivist_user')
    existing_permissions = group.permissions.all()

    for codename in (
        'add_sourcetype',
        'change_sourcetype',
        'view_sourcetype',

        'add_sourcerole',
        'change_sourcerole',
        'view_sourcerole'):
        permission = Permission.objects.get(codename=codename)
        if permission not in existing_permissions:
            group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0017_archivist_rights_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(populate_initial_terms),
        migrations.RunPython(populate_permissions),
    ]
