# Generated by Django 3.1.8 on 2022-01-10 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0020_auto_20220110_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
