# Generated by Django 3.1.8 on 2022-01-10 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0021_appraisal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='note',
            field=models.TextField(default='', null=True),
        ),
    ]
