# Generated by Django 3.2.11 on 2022-01-17 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0022_alter_appraisal_appraisal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
