# Generated by Django 3.1.8 on 2022-01-10 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0022_archivist_submission_appraisal_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bag',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='bag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.bag'),
        ),
    ]
