# Generated by Django 3.2.11 on 2022-01-19 20:33

from django.db import migrations, models
import recordtransfer.models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0023_bag_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='old_copy_removed',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='path',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file_upload',
            field=models.FileField(null=True, storage=recordtransfer.storage.UploadedFileStorage, upload_to=recordtransfer.models.session_upload_location),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='-', max_length=256, null=True),
        ),
    ]
