# Generated by Django 3.1.8 on 2022-01-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0023_auto_20220110_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='accession_identifier',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
