# Generated by Django 3.2.11 on 2022-01-12 19:26

from django.db import migrations

from dbtemplates.models import Template


RECORDTRANSFER_PREFIX = 'recordtransfer'

def populate_templates(apps, schema_editor):
    ''' Add default editable templates to database '''

    for name in (
            'about',
            'activationcomplete',
            'activationinvalid',
            'activationsent',
            'banner',
            'base',
            'footer',
            'header',
            'home',
            'transfersent',
            'transferform_legal',
        ):
        template_name = RECORDTRANSFER_PREFIX + '/' + name + '.html'
        template, _ = Template.objects.get_or_create(
            name=template_name,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('recordtransfer', '0025_user_gets_notification_emails'),
        ('dbtemplates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_templates),
    ]
