# Generated by Django 3.2.11 on 2022-01-12 19:26

from django.db import migrations

from dbtemplates.models import Template


RECORDTRANSFER_PREFIX = 'recordtransfer'

def populate_templates(apps, schema_editor):
    ''' Add default editable templates to database '''

    for name, description in (
            ('about', (
                'Page for information relating to the application.'
            )),
            ('activationcomplete', (
                'Page user is re-directed to after activating their account.'
            )),
            ('activationinvalid', (
                'Page user is re-directed to if their account could not be '
                'activated.'
            )),
            ('activationsent', (
                'Page user is re-directed to after submitting their info in '
                'the sign-up form.'
            )),
            ('banner', (
                'Banner displayed at top of every page of site.'
            )),
            ('base', (
                'Base template used for every page of site. Includes the head '
                'so that the title, scripts, meta tags, etc. can be edited.'
            )),
            ('footer', (
                'Footer displayed on every page of site.'
            )),
            ('header', (
                'Navigation header displayed on every page of site.'
            )),
            ('home', (
                'Main homepage or "index" page.'
            )),
            ('transfersent', (
                'Page user is re-directed to after submitting a transfer.'
            )),
            ('transferform_legal', (
                'First page of transfer form that contains legal copy defining '
                'the legal parameters that apply to the transfer. Legal copy '
                'should be defined the form_explanation block.'
            )),
        ):
        template_name = RECORDTRANSFER_PREFIX + '/' + name + '.html'
        template, _ = Template.objects.get_or_create(
            name=template_name,
            description=description,
        )


class Migration(migrations.Migration):
    dependencies = [
        ('recordtransfer', '0025_user_gets_notification_emails'),
        ('dbtemplates', '0002_add_template_description'),
    ]

    operations = [
        migrations.RunPython(populate_templates),
    ]
