# Generated by Django 3.2.11 on 2022-07-04 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0008_rights_types'),
        ('recordtransfer', '0027_savedtransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='accession_identifier',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='level_of_detail',
        ),
        migrations.AddField(
            model_name='submission',
            name='bag_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='part_of_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.baggroup'),
        ),
        migrations.AddField(
            model_name='submission',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.uploadsession'),
        ),
        migrations.AddField(
            model_name='submission',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='submission',
            name='bag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='caais.metadata'),
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='Right',
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals',
                                    to='recordtransfer.submission'),
        ),
    ]
