# Generated by Django 3.2.11 on 2022-11-07 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caais', '0010_alter_archivalunit_archival_unit'),
        ('recordtransfer', '0028_remove_submission_bag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='bag',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='caais.metadata'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recordtransfer.uploadsession'),
        ),
    ]
