# Generated by Django 3.2.18 on 2023-03-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0029_auto_20221107_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SourceRole',
        ),
        migrations.DeleteModel(
            name='SourceType',
        ),
    ]
