# Generated by Django 3.2.20 on 2023-07-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0030_auto_20230313_0924'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BagGroup',
            new_name='SubmissionGroup',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='bag',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gets_bag_email_updates',
            new_name='gets_submission_email_updates',
        ),
        migrations.AlterField(
            model_name='submission',
            name='upload_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordtransfer.uploadsession'),
        ),
    ]
