# Generated by Django 3.2.20 on 2023-11-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0032_delete_appraisal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='review_status',
        ),
    ]
