# Generated by Django 4.2.17 on 2025-01-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0041_uploadedfile_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='session',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='recordtransfer.uploadsession'),
            preserve_default=False,
        ),
    ]
