# Generated by Django 4.2.18 on 2025-01-16 14:53

from django.db import migrations, models
import django.db.models.deletion
import recordtransfer.models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0042_alter_uploadedfile_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=256, null=True)),
                ('file_upload', models.FileField(null=True, storage=recordtransfer.storage.UploadedFileStorage, upload_to=recordtransfer.models.session_upload_location)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordtransfer.uploadsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TempUploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=256, null=True)),
                ('file_upload', models.FileField(null=True, storage=recordtransfer.storage.TempFileStorage, upload_to=recordtransfer.models.session_upload_location)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordtransfer.uploadsession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
