# Generated by Django 4.2.18 on 2025-01-16 15:39

from django.db import migrations, models
import recordtransfer.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0043_storeduploadedfile_tempuploadedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storeduploadedfile',
            name='file_upload',
            field=models.FileField(null=True, storage=recordtransfer.storage.UploadedFileStorage, upload_to=''),
        ),
    ]
