# Generated by Django 4.2.18 on 2025-01-23 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0043_split_file_into_two_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
