# Generated by Django 4.2.18 on 2025-01-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0043_storeduploadedfile_tempuploadedfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadsession',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
