# Generated by Django 4.2.18 on 2025-01-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0044_uploadsession_expired'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoredUploadedFile',
            new_name='PermUploadedFile',
        ),
    ]
