# Generated by Django 4.2.18 on 2025-01-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0045_rename_storeduploadedfile_permuploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permuploadedfile',
            options={'verbose_name': 'Permanent uploaded file', 'verbose_name_plural': 'Permanent uploaded files'},
        ),
        migrations.AlterModelOptions(
            name='tempuploadedfile',
            options={'verbose_name': 'Temporary uploaded file', 'verbose_name_plural': 'Temporary uploaded files'},
        ),
    ]
