# Generated by Django 4.2.18 on 2025-01-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordtransfer', '0046_alter_permuploadedfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadsession',
            name='expired',
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='status',
            field=models.CharField(choices=[('CR', 'Session Created'), ('EX', 'Session Expired'), ('TF', 'All Files in Temporary Storage'), ('CP', 'Copying Files to Permanent Storage'), ('PF', 'All Files in Permanent Storage'), ('FD', 'Copying Failed')], default='CR', max_length=2),
        ),
    ]
