# Generated by Django 5.2.5 on 2025-08-21 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import upload.models
import upload.storage


class Migration(migrations.Migration):
    """Move file models from recordtransfer to this app."""

    initial = True

    dependencies = [  # noqa: RUF012
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [  # noqa: RUF012
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="UploadSession",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("token", models.CharField(max_length=32)),
                        ("started_at", models.DateTimeField()),
                        (
                            "status",
                            models.CharField(
                                choices=[
                                    ("CR", "Session Created"),
                                    ("EX", "Session Expired"),
                                    ("UG", "Uploading Files"),
                                    ("CP", "File Copy in Progress"),
                                    ("SD", "All Files in Permanent Storage"),
                                    ("FD", "Copying Failed"),
                                    ("RP", "File Removal in Progress"),
                                ],
                                default="CR",
                                max_length=2,
                            ),
                        ),
                        ("last_upload_interaction_time", models.DateTimeField(auto_now_add=True)),
                        (
                            "user",
                            models.ForeignKey(
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                ),
                migrations.CreateModel(
                    name="TempUploadedFile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(default="-", max_length=256, null=True)),
                        (
                            "file_upload",
                            models.FileField(
                                null=True,
                                storage=upload.storage.TempFileStorage,
                                upload_to=upload.models.session_upload_location,
                            ),
                        ),
                        (
                            "session",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="upload.uploadsession",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "File Currently Being Uploaded",
                        "verbose_name_plural": "Files Currently Being Uploaded",
                        "abstract": False,
                    },
                ),
                migrations.CreateModel(
                    name="PermUploadedFile",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("name", models.CharField(default="-", max_length=256, null=True)),
                        (
                            "file_upload",
                            models.FileField(
                                null=True, storage=upload.storage.UploadedFileStorage, upload_to=""
                            ),
                        ),
                        (
                            "session",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="upload.uploadsession",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Permanent uploaded file",
                        "verbose_name_plural": "Permanent uploaded files",
                        "abstract": False,
                    },
                ),
            ],
        ),
        # Change the user field to use the generic user model
        # This is so that we're not dependent on the recordtransfer app
        migrations.AlterField(
            model_name="uploadsession",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
