# Generated by Django 5.2.13 on 2026-05-05 20:03

from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations


def add_archivist_permissions(apps, schema_editor) -> None:
    """Add upload object permissions to archivist_user group."""
    emit_post_migrate_signal(1, False, "default")

    group, _ = Group.objects.get_or_create(name="archivist_user")
    existing_permissions = group.permissions.all()

    permission_specs = [
        # (app_label, model, codename)
        ("upload", "permuploadedfile", "view_permuploadedfile"),
        ("upload", "tempuploadedfile", "view_tempuploadedfile"),
        ("upload", "uploadsession", "view_uploadsession"),
    ]

    for app_label, model, codename in permission_specs:
        try:
            content_type = ContentType.objects.get(app_label=app_label, model=model)
            permission = Permission.objects.get(codename=codename, content_type=content_type)
            if permission not in existing_permissions:
                group.permissions.add(permission)
        except (Permission.DoesNotExist, ContentType.DoesNotExist):
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_archivist_permissions),
    ]
