name: Check for Unmigrated Model Changes

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipx
        run: python -m pip install --upgrade pip && pip install pipx

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check for unmigrated changes
        run: |
          python manage.py makemigrations --check
