name: Check for Unmigrated Model Changes

on:
  pull_request:
    paths:
      - "**.py"
    branches:
      - master
      - "feat-*"
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Check for unmigrated changes
        run: uv run python app/manage.py makemigrations --check
