name: Check for Unmigrated Model Changes

on:
  pull_request:
    paths:
      - "**.py"
    branches:
      - master
      - "feat-*"
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.8.8"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Check for unmigrated changes
        run: uv run python app/manage.py makemigrations --check
