name: Run Django Unit Tests

on:
  pull_request:
    paths:
      - '**.py'
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.2"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --locked --extra dev

      - name: Run unit tests
        run: uv run pytest -k unit
