name: PR Python Lint Check

on:
  pull_request:
    paths:
      - '**.py'
      - ruff.toml

    branches:
      - master
      - 'feat-*'

    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-python:
    name: Lint RecordTransfer and CAAIS Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          src: >-
            ./app/recordtransfer ./app/caais ./app/nginx ./app/upload ./app/utility
          version-file: "./pyproject.toml"
          args: "--config ./ruff.toml check --exclude app/recordtransfer/migrations/ --exclude app/recordtransfer/tests/ --exclude app/caais/migrations/ --exclude app/caais/tests/ --exclude app/nginx/tests/ --exclude app/upload/migrations/ --exclude app/upload/tests/ --exclude app/utility/tests/"