name: PR Lint Check

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  lint:
    name: Run JS Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting check
        run: npm run lint
