name: Production Smoke Test Podman (via compose.prod.yml)

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Copy environment file
        run: cp example.prod.env .prod.env

      - name: Add SECRET_KEY to environment file
        run: |
          echo -e "\nSECRET_KEY=${{ secrets.SECRET_KEY }}" >> .prod.env

      - name: Set up Podman and dependencies
        run: |
            sudo apt-get update
            sudo apt-get -y install podman

            pip install uv
            uv sync --extra dev --extra podman
            # Install podman-compose directly and make sure it's in PATH
            pip install podman-compose==1.3.0

            # Verify installations
            podman --version
            podman-compose --version

            echo -e "[engine]\nvolumes_dir=\"/home/runner/.local/share/containers/storage/volumes\"" | sudo tee /etc/containers/containers.conf
            podman info

      - name: Start containers
        run: podman-compose -f compose.prod.yml up -d --build

      - name: Wait for database to be ready
        run: |
            echo "Waiting for database to initialize..."
            timeout=180  # Increased to 3 minutes
            elapsed=0
            db_ready=false

            until [ $elapsed -ge $timeout ] || [ "$db_ready" = true ]; do
            # Check if MySQL shows "ready for start up" message first
            if podman-compose -f compose.prod.yml logs db | grep -q "MySQL init process done. Ready for start up"; then
                echo "✅ MySQL initialization complete, waiting for container to be fully running..."

                # Keep waiting until the container status changes from (starting) to fully running
                until podman ps --filter name=db | grep -q "Up" && ! podman ps --filter name=db | grep -q "(starting)"; do
                echo "⏳ MySQL container still in starting state, waiting..."
                sleep 10
                elapsed=$((elapsed+10))

                if [ $elapsed -ge $timeout ]; then
                    echo "❌ Timeout waiting for MySQL to fully start"
                    break
                fi
                done

                echo "✅ MySQL container is now fully running"

                # Give MySQL a moment to start accepting connections after container is fully up
                echo "Waiting 10 more seconds for MySQL to be ready for connections..."
                sleep 10
                db_ready=true
                break
            fi

            sleep 5
            elapsed=$((elapsed+5))
            echo "DB still initializing... ($elapsed/$timeout seconds)"
            done

            if [ $elapsed -ge $timeout ]; then
            echo "❌ Database initialization timed out. Logs:"
            podman-compose -f compose.prod.yml logs db
            podman ps -a
            exit 1
            fi

            # Quick check to see if MySQL is responding
            echo "Testing MySQL connection..."
            max_attempts=5
            for attempt in $(seq 1 $max_attempts); do
            echo "Connection attempt $attempt/$max_attempts"
            if podman exec secure-record-transfer_db_1 mysqladmin ping -h localhost -u root --silent; then
                echo "✅ MySQL is responding to ping requests!"
                break
            elif [ $attempt -eq $max_attempts ]; then
                echo "❌ MySQL is not responding after $max_attempts attempts"
                podman-compose -f compose.prod.yml logs db
                exit 1
            else
                echo "⚠️ MySQL ping failed, retrying in 5 seconds..."
                sleep 5
            fi
            done

            echo "✅ Database is ready! Proceeding to app startup."

      - name: Wait for app to start
        run: |
          timeout=30
          elapsed=0
          echo "Waiting for application to be ready (will time out after ${timeout}s)..."
          until [ $elapsed -ge $timeout ] || podman-compose -f compose.prod.yml logs app | grep -q "Listening at: http://0.0.0.0:8000"; do
            sleep 5
            elapsed=$((elapsed+5))
            echo "Still waiting... ($elapsed/$timeout seconds elapsed)"
          done
          if [ $elapsed -ge $timeout ]; then
            echo "Timeout reached. Application did not start properly."
            podman-compose -f compose.prod.yml logs app
            exit 1
          fi
          echo "Application is ready!"

      # The port number is set in the compose.prod.yml file
      - name: Check homepage status
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:1337/)
          if [ $response -eq 200 ]; then
            echo "Homepage is returning 200 OK in production configuration"
            exit 0
          else
            echo "Homepage returned status code $response in production configuration"
            exit 1
          fi

      - name: Stop containers
        if: always()
        run: podman-compose -f compose.prod.yml down -v
