name: Sync Ruff Configuration

on:
  schedule:
    - cron: "0 0 * * 0" # Runs every week
  workflow_dispatch:

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Fetch ruff.toml from NCTR's Python Development Guide
        run: |
          curl -o ./ruff_new.toml https://raw.githubusercontent.com/NationalCentreTruthReconciliation/Python-Development-Guide/main/ruff.toml

      - name: Check for changes
        id: check_changes
        run: |
          if ! cmp -s ./ruff_new.toml ./ruff.toml; then
            echo "changes_detected=true" >> $GITHUB_OUTPUT
            mv ./ruff_new.toml ./ruff.toml
          else
            rm ./ruff_new.toml
            echo "changes_detected=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Sync ruff.toml from NationalCentreTruthReconciliation/Python-Development-Guide"
          branch: sync-ruff-config
          delete-branch: true
          title: "Sync ruff.toml from NationalCentreTruthReconciliation/Python-Development-Guide"
          body: "This PR syncs the ruff.toml file from NationalCentreTruthReconciliation/Python-Development-Guide."
          base: master
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
